function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(5)=1;
    ys_(9)=1;
    ys_(6)=1/params(2)+params(3)-1;
    K_L=(ys_(5)*ys_(9)*params(1)/ys_(6))^(1/(1-params(1)));
    ys_(7)=ys_(5)*ys_(9)*(1-params(1))*K_L^params(1);
    IV_L=params(3)*K_L;
    Y_L=ys_(5)*K_L^params(1);
    C_L=Y_L-IV_L;
    L0=0.3333333333333333;
    ys_(4)=rbc_steady_state_helper(L0,ys_(7),C_L,params(6),params(7),params(5),params(4));
    ys_(2)=C_L*ys_(4);
    ys_(1)=Y_L*ys_(4);
    ys_(8)=IV_L*ys_(4);
    ys_(3)=K_L*ys_(4);
    % Auxiliary equations
end
